routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'periodo.inscricao']], function() {
    Route::resource('projects', 'ProjetoController');
    Route::resource('orientadors', 'OrientadorController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('ajax-subareas', 'ProjetoController@getSubAreas')->name('getSubAreas');
});

Route::resource('alunos', 'AlunoController');
Route::resource('avaliadores', 'AvaliadorController');
Route::resource('voluntarios', 'VoluntarioController');
Route::post('/contato', 'ContactController@post')->name('contato');

Route::get('participante', 'AlunoController@participante')->name('participante.create');
Route::get('documentos', 'HomeController@documentos')->name('documentos');


Auth::routes();

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
                @endif
                <div class="card-header">Página do Administrador</div>
                @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
                @endif
                <div class="card-body">
                    
                    <div class="accordion" id="accordionExample">
                        <div class="card">
                          <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                Relatórios
                              </button>
                            </h5>
                          </div>
                      
                          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                              <a href="{{ route('projects.index') }}">Projetos</a>
                              <a href="{{ route('alunos.index') }}">Alunos</a>
                              <a href="{{ route('orientadors.index') }}">Orientadores</a>
                              <a href="{{ route('avaliadores.index') }}">Avaliadores</a>
                              <a href="{{ route('voluntarios.index') }}">Voluntários</a>
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                2° Passo 
                              </button>
                            </h5>
                          </div>
                          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                            <div class="card-body">
                              
                              
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingThree">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                3° 
                              </button>
                            </h5>
                          </div>
                          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                            <div class="card-body">
                        

                                
                    
                            </div>
                          </div>
                        </div>
                      </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/avaliador.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
                @endif
                <div class="card-header">Página do Avaliador</div>
                @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
                @endif
                <div class="card-body">
                    <div class="alert alert-success">
                      <br />
                      <h3>Parabéns seu cadastro foi registrado.</h3>
                      <br />
                      <p>Neste espaço você ira receber informações e poderá avaliar os projetos!</p>
                      <br />
                      <p>Aguarde que dentro de alguns dias os projetos devem começar a aparecer!</p>
                      <br />       
                      <p><b>Obrigado!</b></p>
                    </div>
            {{--         <div class="accordion" id="accordionExample">
                        <div class="card">
                          <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                1° Passo 
                              </button>
                            </h5>
                          </div>                    
                          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">

                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                2° Passo 
                              </button>
                            </h5>
                          </div>
                          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                            <div class="card-body">
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingThree">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                3° 
                              </button>
                            </h5>
                          </div>
                          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                            <div class="card-body">
                            </div>
                          </div>
                        </div>
                      </div> --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/documentos.blade.php
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>FEPARCIT</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <!--
			CSS
			============================================= -->
    <link rel="stylesheet" href="css/linearicons.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/nice-select.css">
    <link rel="stylesheet" href="css/animate.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/estilo.css">
    <style>
        body{
            background: none;
        }
    </style>
</head>

<body>
    <!-- Start info Area -->
    <section class="info-area" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mb-30">

                </div>
            </div>
            <div class="row">
                <h1 class="m-5">Biblioteca de documentos</h1>
                <table class="table table-striped">
                    <tr>
                        <th width="90%">Descrição do documento</th>
                        <th width="10%" colspan="2">Tipo de download</th>
                    </tr>
                    <tr>
                        <td>Autorização de direitos intelectuais e uso de imagem para maiores de idade</td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_direitos_intelectuais_e_uso_de_imagem_para_maiores_de_idade.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_direitos_intelectuais_e_uso_de_imagem_para_maiores_de_idade.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Autorização de direitos intelectuais e uso de imagem para menores de idade</td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_direitos_intelectuais_e_uso_de_imagem_para_menores_de_idade.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_direitos_intelectuais_e_uso_de_imagem_para_menores_de_idade.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>

                        <td>Autorização de hospedagem para menores de idade</td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_hospedagem_para_menores_de_idade.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_hospedagem_para_menores_de_idade.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Autorização de viagem para alunos menores de idade</td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_viagem_para_alunos_menores_de_idade.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/autorizacao_de_viagem_para_alunos_menores_de_idade.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Formulários para pesquisa com agentes biológicos potencialmente perigosos</td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_agentes_biologicos_potencialmente_perigosos.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_agentes_biologicos_potencialmente_perigosos.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Formulários para pesquisa com animais vertebrados</td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_animais_vertebrados.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_animais_vertebrados.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Formulários para pesquisa com equipamentos de alta periculosidade</td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_equipamentos_de_alta_periculosidade.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_equipamentos_de_alta_periculosidade.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Formulários para pesquisa com seres humanos</td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_seres_humanos.docx') }}">
                                <img src="{{ asset('img/docx.png') }}" width="50" />
                            </a>
                        </td>
                        <td>
                            <a href="{{ asset('docs/formularios_para_pesquisa_com_seres_humanos.pdf') }}">
                                <img src="{{ asset('img/pdf.png') }}" width="50" />
                            </a>
                        </td>
                    </tr>
                    <tr>
                            <td>Formulários para pesquisa com substâncias tóxicas ou controladas</td>
                            <td>
                                <a href="{{ asset('docs/formularios_para_pesquisa_com_substancias_toxicas_ou_controladas.docx') }}">
                                    <img src="{{ asset('img/docx.png') }}" width="50" />
                                </a>
                            </td>
                            <td>
                                <a href="{{ asset('docs/formularios_para_pesquisa_com_substancias_toxicas_ou_controladas.pdf') }}">
                                    <img src="{{ asset('img/pdf.png') }}" width="50" />
                                </a>
                            </td>
                        </tr>
                        <tr>
                                <td>Formulários para pesquisa com tecidos humanos ou de outros vertebrados</td>
                                <td>
                                    <a href="{{ asset('docs/formularios_para_pesquisa_com_tecidos_humanos_ou_de_outros_vertebrados.docx') }}">
                                        <img src="{{ asset('img/docx.png') }}" width="50" />
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ asset('docs/formularios_para_pesquisa_com_tecidos_humanos_ou_de_outros_vertebrados.pdf') }}">
                                        <img src="{{ asset('img/pdf.png') }}" width="50" />
                                    </a>
                                </td>
                            </tr>
                </table>


                <br>
            </div>
        </div>
    </section>
    <!-- End info Area -->

    <script src="js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="js/easing.min.js"></script>
    <script src="js/hoverIntent.js"></script>
    <script src="js/superfish.min.js"></script>
    <script src="js/jquery.ajaxchimp.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.sticky.js"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/parallax.min.js"></script>
    <script src="js/mail-script.js"></script>
    <script src="js/main.js"></script>
</body>

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
                @endif
                <div class="card-header">Meu projeto</div>
                @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
                @endif
                <div class="card-body">
                    
                    <div class="accordion" id="accordionExample">
                        <div class="card">
                          <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                1° Passo - Cadastrar seu projeto
                              </button>
                            </h5>
                          </div>
                      
                          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                              @if (isset($projeto))
                                <table class="table">
                                  <tr>
                                    <th width="90%">Projeto</th><th>Ação</th>
                                  </tr>
                                  <tr>
                                    <td>{{$projeto->nome}}</td>
                                    <td><a href="{{ route('projects.edit', $projeto->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                        <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                    </a></td>
                                  </tr>
                                </table>
                              @else
                                <a href="{{ route('projects.create') }}" class="btn btn-success"> Cadastrar projeto </a>
                              @endif
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                2° Passo - Adicionar dados dos participantes 
                              </button>
                            </h5>
                          </div>
                          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                            <div class="card-body">
                              @if (isset($projeto))
                                <table class="table">
                                  <tr>
                                    <th width="90%">Participante</th><th>Ação</th>
                                  </tr>
                                  @foreach ($alunos as $a)
                                  <tr>
                                    <td>{{$a->nome}}</td>
                                    <td>
                                      <a href="{{ route('alunos.edit', $a->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                        <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                      </a>
                                    </td>  
                                  </tr>  
                                  @endforeach
                                  <tr>
                                    <td></td>
                                    <td>
                                      @if (isset($alunos) && count($alunos) <= 3)
                                      <a href="{{ route('participante.create') }}" title="Incluir aluno" class="btn btn-sm btn-success pull-right edit">
                                          <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Adicionar participante</span>
                                      </a>
                                      @endif
                                    </td>
                                  </tr>
                                </table>
                              @else
                              {{--   <a href="{{ route('projects.create') }}"  class="btn btn-success"> Enviar projeto </a> --}}
                              <p>Realize o primeiro passo para habilitar este item</p>
                              @endif
                              
                            </div>
                          </div>
                        </div>
                        <div class="card">
                          <div class="card-header" id="headingThree">
                            <h5 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                3° Passo - Adicionar dados do orientador
                              </button>
                            </h5>
                          </div>
                          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                            <div class="card-body">
                                @if (isset($projeto))
                                <table class="table">
                                  <tr>
                                    <th width="90%">Orientador</th><th>Ação</th>
                                  </tr>
                                  @if (isset($orientador) && count($orientador) > 0)
                                  @foreach ($orientador as $o)
                                  <tr>
                                    <td>{{$o->nome}}</td>
                                    <td>
                                      <a href="{{ route('orientadors.edit', $o->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                        <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                      </a>
                                    </td>  
                                  </tr>  
                                  @endforeach
                                  @else 
                                    <tr>
                                      <td></td>
                                      <td>
                                        <a href="{{ route('orientadors.create') }}" title="Incluir orientador" class="btn btn-sm btn-success pull-right edit">
                                            <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Adicionar Orientador</span>
                                        </a>
                                      </td>
                                    </tr>
                                  @endif

                                </table>

                                <table class="table">
                                    <tr>
                                      <th width="90%">Coorientador</th><th>Ação</th>
                                    </tr>
                  
                                    @foreach ($coorientador as $co)
                                    <tr>
                                      <td>{{$co->nome}}</td>
                                      <td>
                                        <a href="{{ route('orientadors.edit', $co->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                          <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                        </a>
                                       {{--  <a href="{{ route('orientadors.edit', $co->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                          <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                        </a> --}}
                                      </td>  
                                    </tr>  
                                    @endforeach
                                   
                                      <tr>
                                        <td></td>
                                        <td>
                                          <a href="{{ route('orientadors.create') }}" title="Incluir orientador" class="btn btn-sm btn-success pull-right edit">
                                              <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Adicionar Coorientador</span>
                                          </a>
                                        </td>
                                      </tr>
                                   
  
                                  </table>
                              @else
                                <p>Realize o primeiro passo para habilitar este item</p>

                               {{--  <a href="{{ route('projects.create') }}"  class="btn btn-success"> Enviar projeto </a> --}}
                              @endif
                            </div>
                          </div>
                        </div>
                      </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/voluntario.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        @if (session('success'))
        <div class="alert alert-success">
          {{ session('success') }}
        </div>
        @endif
        <div class="card-header">Página do Voluntário</div>
        @if (session('status'))
        <div class="alert alert-success" role="alert">
          {{ session('status') }}
        </div>
        @endif
        <div class="card-body">
          <div class="alert alert-success">
            <br />
            <h3>Parabéns seu cadastro foi registrado.</h3>
            <br />
            <p>Aguarde que nós entraremos em contado com você no email cadastrado para passar mais informações!</p>
            <br />
            <br />

            <p><b>Obrigado!</b></p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</div>
@endsection