routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'periodo.inscricao']], function() {
    Route::resource('projects', 'ProjetoController');
    Route::resource('orientadors', 'OrientadorController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('ajax-subareas', 'ProjetoController@getSubAreas')->name('getSubAreas');
});

Route::resource('alunos', 'AlunoController');
Route::resource('avaliadores', 'AvaliadorController');
Route::resource('voluntarios', 'VoluntarioController');
Route::post('/contato', 'ContactController@post')->name('contato');

Route::get('participante', 'AlunoController@participante')->name('participante.create');
Route::get('documentos', 'HomeController@documentos')->name('documentos');


Auth::routes();

app/Projeto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Projeto extends Model
{
    protected $table = "projects";

    protected $fillable = [
        'nome',
        'problema',
        'hipotese',
        'materiais',
        'metodos',
        'bibliografia',
        'resumo',
        'cronograma', //PDF //
        'resultado',// 
        'palavras_chave',
        'anexo',//1 arquivo
        'tipo_pesquisa',// 
        'parecer',// Arquivo com paracer da comissão de ética
        'tipo_instituicao',//público e privado
        'nome_instituicao',
        'email_instituicao',
        'telefone_instituicao',
        'status',
        'user_id',
        'subarea_id',
        'categoria', // Ensino médio, Subsequente
        //resumo campo aberto.
        //relatorio final anexo.

        //comentario dos avaliadores....
    ];    

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function subarea()
    {
        return $this->belongsTo('App\Subareas', 'subarea_id');
    }

    public function alunos()
    {
        return $this->belongsToMany('App\Aluno','project_alunos', 'project_id', 'aluno_id')->withTimestamps();
    }

    public function orientadores()
    {
        return $this->belongsToMany('App\Orientador','project_orientadors', 'project_id', 'orientador_id')->withTimestamps();
    }
}

app/Http/Controllers/ProjetoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProjetoRequest;
use App\Projeto;
use App\Areas;
use App\Subareas;
use Auth;
use Illuminate\Support\Facades\Storage;

class ProjetoController extends Controller
{
    public function index()
    {
        $projetos = Projeto::all();
        
        return view('projeto.index', compact('projetos')); 
    }


    public function getSubAreas(Request $request)
    {
        $id = $request->area;
        

        $subareas = Subareas::where('area_id', '=', $id)->get();

        return response()->json($subareas);
    }

    public function show($id)
    {
        $projeto = projeto::find($id);
        
        //return response()->json($projeto);
        return view('projeto.show', compact('projeto'));
    }

    public function update(ProjetoRequest $request, $id)
    {
        $projeto = Projeto::find($id);

        $data = $request->all();

        if ($request->hasFile('cronograma')) {
            $path = $request->file('cronograma')->store('feparcit/cronograma');

            $url = Storage::url($path);

            $data['cronograma'] = $url;
        }

        if ($request->hasFile('parecer')) {
            $path = $request->file('parecer')->store('feparcit/parecer');

            $url = Storage::url($path);

            $data['parecer'] = $url;
        }

        if ($request->hasFile('anexo')) {
            $path = $request->file('anexo')->store('feparcit/anexo');

            $url = Storage::url($path);

            $data['anexo'] = $url;
        }
        $data['status']  = 'pendente';
        $data['user_id'] = Auth::id();
        
        $projeto->update($data);

        return redirect('home')->with('success', 'Projeto alterado com sucesso!');
    }

    public function store(ProjetoRequest $request)
    {
        $data = $request->all();

        if ($request->hasFile('cronograma')) {
            $path = $request->file('cronograma')->store('feparcit/cronograma');

            $url = Storage::url($path);

            $data['cronograma'] = $url;
        }

        if ($request->hasFile('parecer')) {
            $path = $request->file('parecer')->store('feparcit/parecer');

            $url = Storage::url($path);

            $data['parecer'] = $url;
        }

        if ($request->hasFile('anexo')) {
            $path = $request->file('anexo')->store('feparcit/anexo');

            $url = Storage::url($path);

            $data['anexo'] = $url;
        }
        $data['status']  = 'pendente';
        $data['user_id'] = Auth::id();
        $data['subarea_id'] = 1;
        
        $projeto = Projeto::create($data);

        return redirect('home')->with('success', 'Projeto adicionado');
    }

    public function destroy($id)
    {
       
    }

    public function create()
    {
        $tipo_pesquisa = array(
            [ "id" => "", "name" => "Escolha"],
            [ "id" => "1", "name" => "Pesquisa com seres humanos"],
            [ "id" => "2", "name" => "Pesquisa com animais vertebrados"],
            [ "id" => "3", "name" => "Pesquisa com agentes biologicos potencialmente perigosos"],
            [ "id" => "4", "name" => "Pesquisa com equipamentos ou substâncias controladas"],
            [ "id" => "5", "name" => "Pesquisa não envolve nenhum dos itens citados"],
        );
        $tipo_instituicao = array(
            [ "id" => "1", "name" => "Pública"],
            [ "id" => "2", "name" => "Privada"],
        );
        $areas = Areas::all();
        return view('projeto.create-edit', compact('tipo_pesquisa','tipo_instituicao','areas'));
    }

    public function edit($id)
    {
        $project = Projeto::find($id);
        $tipo_pesquisa = array(
            [ "id" => "", "name" => "Escolha"],
            [ "id" => "1", "name" => "Pesquisa com seres humanos"],
            [ "id" => "2", "name" => "Pesquisa com animais vertebrados"],
            [ "id" => "3", "name" => "Pesquisa com agentes biologicos potencialmente perigosos"],
            [ "id" => "4", "name" => "Pesquisa com equipamentos ou substâncias controladas"],
            [ "id" => "5", "name" => "Pesquisa não envolve nenhum dos itens citados"],
        );
        $tipo_instituicao = array(
            [ "id" => "1", "name" => "Pública"],
            [ "id" => "2", "name" => "Privada"],
        );
        $areas = Areas::all();
        return view('projeto.create-edit', compact('project', 'tipo_pesquisa','tipo_instituicao','areas'));
    }
}

resources/views/projeto/create-edit.blade.php
@extends('layouts.app')
@section('content')
<div class="page-content edit-add container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-bordered">
                <h1 class="page-title"><i class="voyager-alarm-clock"></i>{{isset($project) ? 'Editar projeto' :
                    'Cadastrar projeto'}}</h1>
                @if ($errors->any())
                <div class='alert alert-danger'>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @if (isset($project))
                <form method="post" action="{{route('projects.update', ['id'=>$project->id])}}" enctype="multipart/form-data">
                    {!! method_field('PUT')!!}
                    @else
                    <form action="{{route('projects.store')}}" method='post' enctype="multipart/form-data">
                        @endif
                        {{ csrf_field() }}

                        <div class="panel-body row">
                            <div class="form-group col-md-12">
                                <label>Categoria</label>
                                <select name="categoria" class="form-control">
                                    <option value="">selecione</option>
                                    <option value="1" 
                                        @if(isset($project) && ($project->categoria == 1))
                                            selected
                                        @else
                                            {{ old('categoria') == 1 ? 'selected' : '' }}
                                        @endif
                                        
                                    >Ensino médio</option>
                                    <option value="2"
                                        @if(isset($project) && ($project->categoria == 2))
                                            selected
                                        @else
                                            {{ old('categoria') == 2 ? 'selected' : '' }}
                                        @endif
                                    >Ensino pós médio (Subsequente)</option>
                                </select>
                            </div>

                            <div class="form-group col-md-12">
                                <label>Área do conhecimento</label>
                                <select name="area_id" id="areas" class="form-control">
                                    <option value="">selecione</option>
                                    @foreach ($areas as $a)

                                    <option value="{{$a->id}}" @if(isset($project) && ($project->area_id ==
                                        $a->id))
                                        selected
                                        @else
                                            {{ old('area_id') == $a->id ? 'selected' : '' }}
                                        @endif
                                        >{{$a->nome}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-12">
                                    <label>Sub Área do conhecimento</label>
                                    <select name="subarea_id" id="subareas" class="form-control">
                                        <option value="">selecione</option>
                                    </select>
                                </div>
                            <div class='form-group col-md-12'>
                                <label>Título do projeto</label>
                                <input type="text" name='nome' value='{{$project->nome ?? old("nome")}}' class='form-control' />
                            </div>

                            <div class='form-group col-md-12'>
                                <label>Problema</label>
                                <textarea name='problema' class='form-control'>{{$project->problema ?? old("problema")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Hipótese ou objetivo de engenharia</label>
                                <textarea name='hipotese' class='form-control'>{{$project->hipotese ?? old("nome")}}</textarea>
                            </div>

                            <div class='form-group col-md-12'>
                                <label>Métodos</label>
                                <textarea name='metodos' class='form-control'>{{$project->metodos ?? old("metodos")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Materiais</label>
                                <textarea name='materiais' class='form-control'>{{$project->materiais ?? old("materiais")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Cronograma</label>
                                <input type="file" name='cronograma' value='{{$project->cronograma ?? old("cronograma")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Resultados</label>
                                <textarea name='resultado' class='form-control'>{{$project->resultado ?? old("resultado")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Bibliografia</label>
                                <textarea name='bibliografia' class='form-control'>{{$project->bibliografia ?? old("bibliografia")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Resumo (Máximo 2000 caracteres)</label>
                                <textarea name='resumo' class='form-control'>{{$project->resumo ?? old("resumo")}}</textarea>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Palavras – chave</label>
                                <input type="text" name='palavras_chave' value='{{$project->palavras_chave ?? old("palavras_chave")}}'
                                    class='form-control' />
                            </div>
                            <div class="form-group col-md-12">
                                <label>Pesquisa</label>
                                <select name="tipo_pesquisa" id="tipo_pesquisa" class="form-control">
                                    @foreach ($tipo_pesquisa as $t)

                                    <option value="{{$t['id']}}" 
                                    @if(isset($project) && ($project->tipo_pesquisa == $t['id']))
                                        selected
                                    @else
                                        {{ old('tipo_pesquisa') == $t['id'] ? 'selected' : '' }}
                                    @endif
                                        >{{$t['name']}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="d-none col-md-12" id="anexar_parecer">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label>Parecer comite de Ética</label>
                                        <input type="file" name='parecer' value='{{$project->parecer ?? old("parecer")}}'
                                            class='form-control' />
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>&nbsp;</label>
                                        <a href="{{route('documentos')}}" target="blank" class="btn btn-primary form-control">Download modelo</a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label>Tipo de instituição de ensino</label>
                                <select name="tipo_instituicao" class="form-control">
                                    @foreach ($tipo_instituicao as $t)

                                    <option value="{{$t['id']}}" @if(isset($project) && ($project->tipo_instituicao ==
                                        $t['id']))
                                        selected
                                        @endif
                                        >{{$t['name']}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Nome Instituição</label>
                                <input type="text" name='nome_instituicao' value='{{$project->nome_instituicao ?? old("nome_instituicao")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Email Instituição</label>
                                <input type="text" name='email_instituicao' value='{{$project->email_instituicao ?? old("email_instituicao")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Telefone Instituição</label>
                                <input type="text" name='telefone_instituicao' value='{{$project->telefone_instituicao ?? old("telefone_instituicao")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-12'>
                                <label>Anexo</label>
                                <input type="file" name='anexo' value='{{$project->anexo ?? old("anexo")}}' class='form-control' />
                            </div>
                        </div><!-- panel-body -->

                        <div class="panel-footer">
                            <div style="padding-left: 15px; padding-bottom: 15px;">
                                <!--   <button type="submit" class="btn btn-primary save">Salvar</button> -->
                                @if (isset($project))
                                <button type='submit' class='btn btn-primary '>Alterar</button>
                                @else
                                <button type="submit" class="btn btn-primary ">Salvar</button>
                                @endif
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        



        $("#tipo_pesquisa").on('change', function (e) {
        
            var tipo_pesquisa = e.target.value;

            if (tipo_pesquisa < 5) {
                $("#anexar_parecer").removeClass('d-none');
            } else {
                $("#anexar_parecer").addClass('d-none');
            }
        });

        $("#areas").on('change', function(e){
        var area = e.target.value;
        console.log(area);
        $.get("/ajax-subareas?area=" + area, function(data){
            console.log(data);
            $("#subareas").empty();             
            $("#subareas").append("<option value=''>Selecione</option>");
            $.each(data, function(index, subarea){
                //console.log(subarea);
            if(subarea.id == @php echo (null !== old('subarea_id')) ?  old('subarea_id') : '-1'@endphp )
                $("#subareas").append("<option value='"+ subarea.id +"' selected>" + subarea.nome + "</option>");
            else
                $("#subareas").append("<option value='"+ subarea.id +"'>" + subarea.nome + "</option>");
            });
        });
    });
    $("#areas").trigger('change');
    });
</script>
@stop

resources/views/projeto/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <h1 class="page-title">
        <i class="voyager-categories"></i> Projetos
        <a href="{{ route('home') }}" class="btn btn-success btn-add-new">
            <i class="voyager-plus"></i> <span>Voltar</span>
        </a>
    </h1>

</div>

<div id="voyager-notifications">
    @foreach (['danger', 'warning', 'success', 'info'] as $key)
    @if(Session::has($key))
    <p class="alert alert-{{ $key }}">{{ Session::get($key) }}</p>
    @endif
    @endforeach
</div>


<div class="page-content browse container-fluid">
    <div class="alerts">
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-bordered">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="dataTable3" class="table table-hover" width="100%">
                            <thead>
                                <tr>
                                    <th>Data</th>
                                    <th>Nome</th>
                                    <th>Categoria</th>
                                    <th>Área</th>
                                    <th>Sub Área</th>
                                    <th>Alunos</th>
                                    <th>Orientadores</th>
                                    {{-- <th class="actions text-right">Ações</th> --}}
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($projetos as $p)
                                <tr>
                                    <td>
                                        @php
                                        $date = new DateTime($p->created_at);
                                        echo $date->format('d/m/Y');

                                        @endphp
                                    </td>
                                    <td>{{$p->nome}}</td>

                                    <td>{{$p->categoria=='2' ? 'Subsequente' : 'Ensino médio'}}</td>

                                    <td>{{$p->subarea->area->nome}}</td>
                                    <td>{{$p->subarea->nome}}</td>

                                    <td>{{$p->user->name}}<br />
                                        @foreach ($p->alunos as $aluno)
                                        {{$aluno->nome}} <br />
                                        @endforeach
                                    </td>
                                    <td>
                                        @foreach ($p->orientadores as $orientador)
                                        {{$orientador->nome}} <br />
                                        @endforeach
                                    </td>
                                    {{-- <td>{{$p->orientadores}}</td> --}}
                                    {{-- <td>
                                        <a href="javascript:;" title="Remover" class="btn btn-sm btn-danger pull-right delete"
                                            data-id="{{$c->id}}" id="delete-2">
                                            <i class="voyager-trash"></i> <span class="hidden-xs hidden-sm">Remover</span>
                                        </a>
                                        <a href="{{ route('categories.edit', $c->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                            <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                        </a>
                                        <a href="{{ route('clients.show', $c->id) }}" title="Ver" class="btn btn-sm btn-warning pull-right view">
                                            <i class="voyager-eye"></i> <span class="hidden-xs hidden-sm">Ver</span>
                                        </a>
                                    </td>--}}
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal modal-danger fade" tabindex="-1" id="delete_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-trash"></i> Tem certeza de que deseja remover esta categoria?</h4>
            </div>
            <div class="modal-footer">
                <form action="#" id="delete_form" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <input type="submit" class="btn btn-danger pull-right delete-confirm" value="Sim, Remover!">
                </form>
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cancelar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>
</div>
</div>
</div>

<!-- DataTables -->
<script>
    $(document).ready(function () {
        var table = $('#dataTable3').DataTable({
            responsive: true,
            "order": [],
            "language": {
                "sEmptyTable": "N\u00e3o h\u00e1 registros para apresentar",
                "sInfo": "Mostrando de _START_ at\u00e9 _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando de 0 at\u00e9 0 de 0 registros",
                "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                "sInfoPostFix": "",
                "sInfoThousands": ",",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sLoadingRecords": "A Carregar...",
                "sProcessing": "A processar...",
                "sSearch": "Procurar:",
                "sZeroRecords": "N\u00e3o foram encontrados resultados",
                "oPaginate": {
                    "sFirst": "Primeiro",
                    "sLast": "\u00daltimo",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": ativar para ordenar de forma crescente",
                    "sSortDescending": ": ativar para ordenar de forma decrescente"
                }
            },
            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: -1 }
            ]
        });

        $('.select_all').on('click', function (e) {
            $('input[name="row_id"]').prop('checked', $(this).prop('checked'));
        });
    });


    var deleteFormAction;
    $('td').on('click', '.delete', function (e) {
        $('#delete_form')[0].action = 'categories/__id'.replace('__id', $(this).data('id'));
        $('#delete_modal').modal('show');
    });

</script>
@stop