routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'periodo.inscricao']], function() {
    Route::resource('projects', 'ProjetoController');
    Route::resource('orientadors', 'OrientadorController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('ajax-subareas', 'ProjetoController@getSubAreas')->name('getSubAreas');
});

Route::resource('alunos', 'AlunoController');
Route::resource('avaliadores', 'AvaliadorController');
Route::resource('voluntarios', 'VoluntarioController');
Route::post('/contato', 'ContactController@post')->name('contato');

Route::get('participante', 'AlunoController@participante')->name('participante.create');
Route::get('documentos', 'HomeController@documentos')->name('documentos');


Auth::routes();

app/Aluno.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aluno extends Model
{
    protected $table = "alunos";

    protected $fillable = [
        'nome',
        'rg',
        'cpf',
        'sexo',
        'cep',
        'endereco',
        'cidade',
        'telefone',
        'celular',
        'email',
        'tamanho_camiseta',//fazer no formulário
        'possui_necessidade_especial',
        'necessidade_especial',
        'data_nascimento',
    ];


    public function projetos()
    {
        return $this->belongsToMany('App\Projeto','project_alunos', 'aluno_id', 'project_id')->withTimestamps();
    }

}

app/Http/Controllers/AlunoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\AlunoRequest;
use Westsoft\Acl\Models\UserProfiles;
use Illuminate\Support\Facades\Hash;
use App\Aluno;
use App\Projeto;
use Auth;
use App\User;

class AlunoController extends Controller
{
    public function index()
    {
        $alunos = Aluno::all();
        return view('aluno.index', compact('alunos'));
    }

    public function show($id)
    {
      /*  $projeto = projeto::find($id);
        
        //return response()->json($projeto);
        return view('projeto.show', compact('projeto'));*/
        return view('errors.404');

    }

    public function update(AlunoRequest $request, $id)
    {
        $data = $request->all();
        
        $aluno = Aluno::find($id);
                
        $aluno->update($data);

        return redirect('home')->with('success', 'Dados do aluno alterados.');
    }

    public function store(AlunoRequest $request)
    {
        $data = $request->all();
        
        $aluno = Aluno::create($data);

        if(Auth::id() == null){
            $user = User::create([
                'name' => $data['nome'],
                'email' => $data['email'],
                'password' => Hash::make($data['senha']),
            ]);
                    
            //$user_id = Auth::id();
            
            
            $data['user_id'] = $user->id;
    
    
            $user_profile['profiles_id'] = 4; //Aluno
            $user_profile['users_id'] = $user->id;
    
            $user_profiles = UserProfiles::create($user_profile);   
            
            if (Auth::attempt(['email' => $data['email'], 'password' => $data['senha']]))
            {
                return redirect()->intended('home');
            }
        }

        if($projeto = Projeto::where('user_id', Auth::id())->first()){
            $projeto->alunos()->attach($aluno->id);
        }
        return redirect()->intended('home');
    }

    public function destroy($id)
    {      
        $aluno = Aluno::find($id);
                
        $aluno->delete();

        return redirect('home')->with('success', 'Aluno excluído.');
    }

    public function create()
    {
        return view('aluno.create-edit');
    }

    public function participante()
    {
        $participante = true;
        return view('aluno.create-edit', compact('participante'));
    }

    public function edit($id)
    {
        $aluno = Aluno::find($id);
        return view('aluno.create-edit', compact('aluno'));
    }
}

resources/views/aluno/create-edit.blade.php
@extends('layouts.app')
@section('content')
<div class="page-content edit-add container">
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-bordered">
                <h1 class="page-title"><i class="voyager-alarm-clock"></i>{{isset($aluno) ? 'Editar dados do aluno' :
                    'Cadastrar aluno'}}</h1>
                @if ($errors->any())
                <div class='alert alert-danger'>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @if (isset($aluno))
                <form method="post" action="{{route('alunos.update', ['id'=>$aluno->id])}}" enctype="multipart/form-data">
                    {!! method_field('PUT')!!}
                    @else
                    <form action="{{route('alunos.store')}}" method='post' enctype="multipart/form-data">
                        @endif
                        {{ csrf_field() }}
                        <div class="row">
                            <div class='form-group col-md-8'>
                                <label>Nome</label>
                                <input type="text" name='nome' value='{{$aluno->nome ?? old("nome")}}' class='form-control' />
                            </div>

                            <div class='form-group col-md-4'>
                                <label>RG</label>
                                <input type="text" name='rg' value='{{$aluno->nome ?? old("nome")}}' class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                <label>CPF</label>
                                <input type="text" name='cpf' value='{{$aluno->cpf ?? old("cpf")}}' class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                    <label>Sexo</label><br>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="sexo" value="M"
                                            @if(isset($voluntario) && ($voluntario->sexo == "M")) 
                                                checked 
                                            @else
                                                {{ old('sexo')=="M" ? 'checked='.'"'.'checked'.'"' : '' }}
                                            @endif >
                                        <label class="form-check-label" for="inlineRadio1">Masculino</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="sexo" value="F"
                                            @if(isset($voluntario) && ($voluntario->sexo == "F")) 
                                                checked 
                                            @else
                                                {{ old('sexo')=="F" ? 'checked='.'"'.'checked'.'"' : '' }}
                                            @endif >
                                        <label class="form-check-label" for="inlineRadio1">Feminino</label>
                                    </div>
                                </div>



                            <div class='form-group col-md-4'>
                                <label>Telefone</label>
                                <input type="text" name='telefone' value='{{$aluno->telefone ?? old("telefone")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                <label>Celular</label>
                                <input type="text" name='celular' value='{{$aluno->celular ?? old("celular")}}' class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                <label>Data de Nascimento</label>
                                <input type="date" name='data_nascimento' value='{{$aluno->data_nascimento ?? old("data_nascimento")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                <label>cep</label>
                                <input type="text" name='cep' value='{{$aluno->cep ?? old("cep")}}' class='form-control' />
                            </div>
                            <div class='form-group col-md-8'>
                                <label>Endereço</label>
                                <input type="text" name='endereco' value='{{$aluno->endereco ?? old("endereco")}}'
                                    class='form-control' />
                            </div>
                            <div class='form-group col-md-4'>
                                <label>Cidade</label>
                                <input type="text" name='cidade' value='{{$aluno->cidade ?? old("cidade")}}' class='form-control' />
                            </div>
                            <div class='form-group col-md-7'>
                                <label>Email</label>
                                <input type="email" name='email' value='{{$aluno->email ?? old("email")}}' class='form-control' />
                            </div>

                            @if (!isset($participante))
                            <div class='form-group col-md-5'>
                                <label>Senha</label>
                                <input type="password" name='senha' value='{{$aluno->senha ?? old("senha")}}' class='form-control' />
                            </div>
                            @endif
                            <div class="form-group col-md-4">
                                <label>Tamanho camiseta</label>
                                <select name="tamanho_camiseta" class="form-control">
                                    <option value="">Selecione</option>
                                    <option value="P"  
                                        @if(isset($voluntario) && ($voluntario->tamanho_camiseta == "P")) 
                                            selected 
                                        @else
                                            {{ old('tamanho_camiseta')=="P" ? 'selected' : '' }}
                                        @endif>P</option>
                                    <option value="M"
                                        @if(isset($voluntario) && ($voluntario->tamanho_camiseta == "M")) 
                                            selected 
                                        @else
                                            {{ old('tamanho_camiseta')=="M" ? 'selected' : '' }}
                                        @endif>M</option>
                                    <option value="G"
                                        @if(isset($voluntario) && ($voluntario->tamanho_camiseta == "G")) 
                                            selected 
                                        @else
                                            {{ old('tamanho_camiseta')=="G" ? 'selected' : '' }}
                                        @endif>G</option>
                                    <option value="GG"
                                        @if(isset($voluntario) && ($voluntario->tamanho_camiseta == "GG")) 
                                            selected 
                                        @else
                                            {{ old('tamanho_camiseta')=="GG" ? 'selected' : '' }}
                                        @endif>GG</option>
                                </select>
                            </div>


                            <div class="form-group col-md-4">
                                <label>Necessidade especial</label>
                                <select name="possui_necessidade_especial" class="form-control">
                                    <option value="0">Sem necessidade especial</option>
                                    <option value="1">Com necessidade especial</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Caso possua necessidade especial informe</label>
                                <input type="text" name="necessidade_especial" value='{{$aluno->necessidade_especial ?? old("necessidade_especial")}}' class="form-control" />
                                  
                            </div>
                            
                        </div><!-- panel-body -->

                        <div class="panel-footer">
                            <div style="padding-left: 15px; padding-bottom: 15px;">
                                <!--   <button type="submit" class="btn btn-primary save">Salvar</button> -->
                                @if (isset($aluno))
                                <button type='submit' class='btn btn-primary '>Alterar</button>
                                @else
                                <button type="submit" class="btn btn-primary ">Salvar</button>
                                @endif
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/aluno/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <h1 class="page-title">
        <i class="voyager-categories"></i> Alunos 
        <a href="{{ route('home') }}" class="btn btn-success btn-add-new">
            <i class="voyager-plus"></i> <span>Voltar</span>
        </a> 
    </h1>
   
</div>

<div id="voyager-notifications">
    @foreach (['danger', 'warning', 'success', 'info'] as $key)
        @if(Session::has($key))
            <p class="alert alert-{{ $key }}">{{ Session::get($key) }}</p>
        @endif
    @endforeach
</div>


<div class="page-content browse container-fluid">
    <div class="alerts">
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-bordered">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="dataTable3" class="table table-hover" width="100%">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>RG</th>
                                    <th>CPF</th>
                                    <th>Telefone</th>
                                    <th>Email</th>
                                   {{--  <th class="actions text-right">Ações</th> --}}
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($alunos as $a)
                                <tr>
                                    <td>{{$a->nome}}</td>
                                    <td>{{$a->rg}}</td>
                                    <td>{{$a->cpf}}</td>
                                    <td>{{$a->celular}}</td>
                                    <td>{{$a->email}}</td>
                                    {{--       <td>
                                  <a href="javascript:;" title="Remover" class="btn btn-sm btn-danger pull-right delete"
                                            data-id="{{$c->id}}" id="delete-2">
                                            <i class="voyager-trash"></i> <span class="hidden-xs hidden-sm">Remover</span>
                                        </a>
                                        <a href="{{ route('categories.edit', $c->id) }}" title="Editar" class="btn btn-sm btn-primary pull-right edit">
                                            <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Editar</span>
                                        </a> 
                                        <a href="{{ route('clients.show', $c->id) }}" title="Ver" class="btn btn-sm btn-warning pull-right view">
                                            <i class="voyager-eye"></i> <span class="hidden-xs hidden-sm">Ver</span>
                                        </a>
                                    </td>--}}
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal modal-danger fade" tabindex="-1" id="delete_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-trash"></i> Tem certeza de que deseja remover esta categoria?</h4>
            </div>
            <div class="modal-footer">
                <form action="#" id="delete_form" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <input type="submit" class="btn btn-danger pull-right delete-confirm" value="Sim, Remover!">
                </form>
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cancelar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>
</div>
</div>
</div>

<!-- DataTables -->
<script>
    $(document).ready(function () {
        var table = $('#dataTable3').DataTable({
            responsive: true,
            "order": [],
            "language": {
                "sEmptyTable": "N\u00e3o h\u00e1 registros para apresentar",
                "sInfo": "Mostrando de _START_ at\u00e9 _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando de 0 at\u00e9 0 de 0 registros",
                "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                "sInfoPostFix": "",
                "sInfoThousands": ",",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sLoadingRecords": "A Carregar...",
                "sProcessing": "A processar...",
                "sSearch": "Procurar:",
                "sZeroRecords": "N\u00e3o foram encontrados resultados",
                "oPaginate": {
                    "sFirst": "Primeiro",
                    "sLast": "\u00daltimo",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": ativar para ordenar de forma crescente",
                    "sSortDescending": ": ativar para ordenar de forma decrescente"
                }
            },
            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: -1 }
            ]
        });

        $('.select_all').on('click', function (e) {
            $('input[name="row_id"]').prop('checked', $(this).prop('checked'));
        });
    });


    var deleteFormAction;
    $('td').on('click', '.delete', function (e) {
        $('#delete_form')[0].action = 'categories/__id'.replace('__id', $(this).data('id'));
        $('#delete_modal').modal('show');
    });

</script>
@stop